version: '3.7'
  
services:
############################
##  DATA LAKE
############################
  minio:
    image: minio/minio:latest
    platform: linux/amd64
    container_name: minio
    entrypoint: sh
    command:   '-c ''mkdir -p /minio_data/raw && mkdir -p /minio_data/trusted && minio server /minio_data --console-address ":9001"'''
    ports:
      - "9050:9000"
      - "9051:9001"
    hostname: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY: datalake
      MINIO_SECRET_KEY: datalake
    volumes:
      - ./minio/data1:/data


############################
## INGESTAO
############################

  nifi:
      image: fjardim/mds-nifi
      platform: linux/amd64
      container_name: nifi
      hostname: nifi
      volumes:
        - ./nifi/util:/util
        #- ./nifi/database_repository:/opt/nifi/nifi-current/database_repository
        #- ./nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
        #- ./nifi/content_repository:/opt/nifi/nifi-current/content_repository
        #- ./nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
        #- ./nifi/state:/opt/nifi/nifi-current/state
        #- ./nifi/conf:/opt/nifi/nifi-current/conf
        #- ./util:/util
      environment:
        NIFI_WEB_HTTP_PORT: "9090"
        NIFI_WEB_HTTPS_HOST: "nifi"
        TZ: "America/Sao_Paulo"
      command: >
        sh -c "ln -snf /usr/share/zoneinfo/$$TZ /etc/localtime && echo $$TZ > /etc/timezone"
      
      ports:
        - 49090:9090
      deploy:
        resources:
          limits:
            memory: 2g
            #cpus: '0.2'


############################
## PROCESSAMENTO
############################

  spark-master:
    image: fjardim/mds-spark
    platform: linux/amd64
    hostname: spark-master
    container_name: spark-master
    command: 
      - /bin/sh
      - -c
      - |
        /usr/local/spark/sbin/start-master.sh
        start-notebook.sh --NotebookApp.token=''
    ports:
      - 8889:8888
      - 4040:4040
      - 4041:4041
      - 4042:4042
      - 4043:4043
      - 38080:8080
      - 7077:7077
    volumes:
      - ./spark/work:/home/user 
      - ./spark/env:/env 
      - ./util:/util
    deploy:
      resources:
        limits:
          memory: 2g

#############################
## GENERAL

networks:
  datalab:
    driver: bridge
